/*
 * ECE 461 - Spring 2023 - Project 2
 *
 * API for ECE 461/Spring 2023/Project 2: A Trustworthy Module Registry
 *
 * API version: 3.0.2
 * Contact: davisjam@purdue.edu
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// One entry of the history of this package.
type PackageHistoryEntry struct {

	User *User `json:"User"`
	// Date of activity using ISO-8601 Datetime standard in UTC format.
	Date time.Time `json:"Date"`

	PackageMetadata *PackageMetadata `json:"PackageMetadata"`

	Action string `json:"Action"`
}
