/*
 * ECE 461 - Spring 2023 - Project 2
 *
 * API for ECE 461/Spring 2023/Project 2: A Trustworthy Module Registry
 *
 * API version: 3.0.2
 * Contact: davisjam@purdue.edu
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import "go.mongodb.org/mongo-driver/bson/primitive"

type ModelPackage struct {
	ID       primitive.ObjectID `bson:"_id"`
	Metadata *PackageMetadata   `json:"metadata" bson:"metadata"`
	Data     *PackageData       `json:"data" bson:"data"`
}

type PkgResponse struct {
	Metadata *PackageMetadata `json:"metadata" bson:"metadata"`
	Data     *PackageData     `json:"data" bson:"data"`
}
