/*
 * ECE 461 - Spring 2023 - Project 2
 *
 * API for ECE 461/Spring 2023/Project 2: A Trustworthy Module Registry
 *
 * API version: 3.0.2
 * Contact: davisjam@purdue.edu
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// One entry of the history of this package.
type PackageHistoryEntry struct {
	User            *User            `json:"User" bson:"user"`
	Date            string           `json:"Date" bson:"date"` //storing as string will make things easier
	PackageMetadata *PackageMetadata `json:"PackageMetadata" bson:"packagemetadata"`
	Action          string           `json:"Action" bson:"action"`
}
